# Generated by Django 6.0.1 on 2026-01-21 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('fabricante', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('faixa_medicao', models.CharField(blank=True, max_length=100, verbose_name='Faixa de Medição')),
                ('resolucao', models.CharField(blank=True, max_length=50, verbose_name='Resolução')),
                ('incerteza', models.CharField(blank=True, max_length=50, verbose_name='Incerteza')),
                ('certificado_calibracao', models.CharField(blank=True, max_length=100, verbose_name='Certificado de Calibração')),
                ('data_calibracao', models.DateField(blank=True, null=True, verbose_name='Data da Última Calibração')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Validade da Calibração')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Padrão',
                'verbose_name_plural': 'Padrões',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('medicao', 'Instrumento de Medição'), ('ensaio', 'Equipamento de Ensaio'), ('processo', 'Equipamento de Processo')], default='medicao', max_length=20, verbose_name='Tipo')),
                ('fabricante', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('faixa_medicao', models.CharField(blank=True, max_length=100, verbose_name='Faixa de Medição')),
                ('resolucao', models.CharField(blank=True, max_length=50, verbose_name='Resolução')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('periodicidade_calibracao', models.PositiveIntegerField(default=365, help_text='Intervalo em dias entre calibrações', verbose_name='Periodicidade de Calibração (dias)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='cadastro.funcionario', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PontoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(help_text='Ordem do ponto de calibração', verbose_name='Sequência')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Ponto')),
                ('valor_nominal', models.DecimalField(decimal_places=4, help_text='Valor do ponto de calibração', max_digits=10, verbose_name='Valor Nominal')),
                ('unidade', models.CharField(choices=[('mm', 'Milímetros (mm)'), ('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('kg', 'Quilogramas (kg)'), ('g', 'Gramas (g)'), ('°C', 'Graus Celsius (°C)'), ('°F', 'Graus Fahrenheit (°F)'), ('Pa', 'Pascal (Pa)'), ('bar', 'Bar'), ('psi', 'PSI'), ('V', 'Volts (V)'), ('A', 'Ampere (A)'), ('Ω', 'Ohm (Ω)'), ('Hz', 'Hertz (Hz)'), ('rpm', 'RPM'), ('outro', 'Outro')], max_length=20, verbose_name='Unidade')),
                ('tolerancia_mais', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tolerância (+)')),
                ('tolerancia_menos', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tolerância (-)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_calibracao', to='cadastro.instrumento', verbose_name='Instrumento')),
                ('padrao', models.ForeignKey(help_text='Padrão usado para calibrar este ponto', on_delete=django.db.models.deletion.PROTECT, related_name='pontos_calibracao', to='cadastro.padrao', verbose_name='Padrão Utilizado')),
            ],
            options={
                'verbose_name': 'Ponto de Calibração',
                'verbose_name_plural': 'Pontos de Calibração',
                'ordering': ['instrumento', 'sequencia'],
                'unique_together': {('instrumento', 'sequencia')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calibracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Calibração')),
                ('valor_medido', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Medido')),
                ('desvio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Desvio')),
                ('incerteza', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Incerteza')),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('condicional', 'Condicional')], max_length=20, verbose_name='Status')),
                ('certificado', models.CharField(blank=True, max_length=100, verbose_name='Número do Certificado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_executadas', to='cadastro.funcionario', verbose_name='Executado por')),
                ('ponto_calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cadastro.pontocalibracao', verbose_name='Ponto de Calibração')),
            ],
            options={
                'verbose_name': 'Histórico de Calibração',
                'verbose_name_plural': 'Históricos de Calibração',
                'ordering': ['-data_calibracao'],
            },
        ),
    ]
