# Generated by Django 6.0.1 on 2026-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocalibracao',
            name='padrao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='periodicidade_calibracao',
        ),
        migrations.AddField(
            model_name='pontocalibracao',
            name='periodicidade_calibracao',
            field=models.PositiveIntegerField(default=365, help_text='Intervalo em dias entre calibrações para este ponto', verbose_name='Periodicidade de Calibração (dias)'),
        ),
        migrations.DeleteModel(
            name='Padrao',
        ),
    ]
