# Generated by Django 6.0.1 on 2026-01-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_pontocalibracao_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Instrumento',
                'verbose_name_plural': 'Tipos de Instrumento',
                'ordering': ['descricao'],
            },
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='instrumento_controlado',
            field=models.BooleanField(default=False, help_text='Indica se o instrumento é controlado', verbose_name='Instrumento Controlado'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='tipo_instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='cadastro.tipoinstrumento', verbose_name='Tipo de Instrumento'),
        ),
    ]
