# Generated by Django 6.0.1 on 2026-01-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_setor_remove_instrumento_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='cadastro.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_setor', to='cadastro.setor', verbose_name='Setor'),
        ),
    ]
