# Generated by Django 6.0.1 on 2026-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_funcionario_setor_alter_instrumento_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='faixa_medicao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='resolucao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='setor',
        ),
    ]
