# Generated by Django 6.0.1 on 2026-01-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos', to='cadastro.setor', verbose_name='Setor'),
        ),
    ]
