# Generated by Django 6.0.1 on 2026-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_instrumento_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontocalibracao',
            name='valor_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fim da faixa do ponto (ex: 600)', max_digits=10, null=True, verbose_name='Valor Máximo'),
        ),
        migrations.AddField(
            model_name='pontocalibracao',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Início da faixa do ponto (ex: 0)', max_digits=10, null=True, verbose_name='Valor Mínimo'),
        ),
        migrations.AlterField(
            model_name='pontocalibracao',
            name='valor_nominal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor do ponto de calibração (pode ser calculado como média da faixa)', max_digits=10, null=True, verbose_name='Valor Nominal'),
        ),
    ]
