# Generated by Django 6.0.1 on 2026-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_pontocalibracao_valor_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoinstrumento',
            name='documento_qualidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Documento de Qualidade'),
        ),
    ]
