# Generated by Django 4.2.15 on 2026-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_remove_instrumento_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
