# Generated by Django 4.2.15 on 2026-01-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_instrumento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocalibracao',
            name='unidade',
            field=models.CharField(choices=[('mm', 'Milímetros (mm)'), ('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('kg', 'Quilogramas (kg)'), ('g', 'Gramas (g)'), ('°C', 'Graus Celsius (°C)'), ('°F', 'Graus Fahrenheit (°F)'), ('Pa', 'Pascal (Pa)'), ('bar', 'Bar'), ('psi', 'PSI'), ('V', 'Volts (V)'), ('A', 'Ampere (A)'), ('Ω', 'Ohm (Ω)'), ('Hz', 'Hertz (Hz)'), ('rpm', 'RPM'), ('°', 'Graus (°)')], max_length=20, verbose_name='Unidade'),
        ),
    ]
