# Generated by Django 4.2.15 on 2026-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_pontocalibracao_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocalibracao',
            name='periodicidade_calibracao',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='periodicidade_calibracao',
            field=models.PositiveIntegerField(default=365, help_text='Intervalo em dias entre calibrações para este ponto', verbose_name='Periodicidade de Calibração (dias)'),
        ),
        migrations.AlterField(
            model_name='pontocalibracao',
            name='unidade',
            field=models.CharField(choices=[('mm', 'Milímetros (mm)'), ('cm', 'Centímetros (cm)'), ('m', 'Metros (m)'), ('kg', 'Quilogramas (kg)'), ('g', 'Gramas (g)'), ('°C', 'Graus Celsius (°C)'), ('°F', 'Graus Fahrenheit (°F)'), ('Pa', 'Pascal (Pa)'), ('bar', 'Bar (bar)'), ('psi', 'PSI (psi)'), ('V', 'Volts (V)'), ('A', 'Ampere (A)'), ('Ω', 'Ohm (Ω)'), ('Hz', 'Hertz (Hz)'), ('rpm', 'RPM (rpm)'), ('°', 'Graus (°)'), ('Ohms', 'Ohms'), ('Kg', 'Quilogramas (Kg)'), ('m²/s', 'm²/s'), ('HRC', 'Dureza Rockwell C (HRC)'), ('L/min', 'Litros por minuto (L/min)'), ('Bar', 'Bar (Bar)'), ('kgf/cm²', 'Quilograma-força por cm² (kgf/cm²)'), ('μm', 'Micrômetro (μm)'), ('-', 'Sem unidade (-)'), ('V-AC', 'Volts AC (V-AC)'), ('UR', 'Umidade Relativa (UR)'), ('dB', 'Decibel (dB)'), ('outros', 'Outros')], max_length=20, verbose_name='Unidade'),
        ),
    ]
