# Generated by Django 4.2.15 on 2026-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_remove_pontocalibracao_periodicidade_calibracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='finalidade',
            field=models.CharField(blank=True, choices=[('maquina de solda', 'Máquina de Solda'), ('gabarito', 'Gabarito'), ('instrumento de medicao', 'Instrumento de Medição')], max_length=100, verbose_name='Finalidade'),
        ),
    ]
