# Generated by Django 6.0.1 on 2026-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_instrumento_finalidade_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção'), ('descartado', 'Descartado'), ('perdido', 'Perdido')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
