# Generated by Django 6.0.1 on 2026-01-21 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0006_remove_instrumento_faixa_medicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data Fim')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_em_posse', to='cadastro.funcionario')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posses', to='cadastro.instrumento')),
            ],
            options={
                'verbose_name': 'Posse de Instrumento',
                'verbose_name_plural': 'Posses de Instrumentos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaFuncionarioInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='assinaturas/', verbose_name='Imagem da Assinatura')),
                ('data_assinatura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Assinatura')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('posse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='instrumento.funcionarioinstrumento')),
            ],
            options={
                'verbose_name': 'Assinatura de Posse de Instrumento',
                'verbose_name_plural': 'Assinaturas de Posse de Instrumentos',
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='StatusInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Entrega')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data Devolução')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_instrumentos', to='cadastro.funcionario')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_historico', to='cadastro.instrumento')),
            ],
            options={
                'verbose_name': 'Status do Instrumento',
                'verbose_name_plural': 'Status dos Instrumentos',
                'ordering': ['-data_entrega'],
            },
        ),
        migrations.AddIndex(
            model_name='funcionarioinstrumento',
            index=models.Index(fields=['funcionario', 'instrumento'], name='instrumento_funcion_3338d7_idx'),
        ),
        migrations.AddIndex(
            model_name='statusinstrumento',
            index=models.Index(fields=['instrumento', 'funcionario'], name='instrumento_instrum_166b0a_idx'),
        ),
    ]
