# Generated by Django 6.0.1 on 2026-01-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_pontocalibracao_valor_maximo_and_more'),
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinstrumento',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_status_instrumentos', to='cadastro.funcionario'),
        ),
        migrations.AddField(
            model_name='statusinstrumento',
            name='tipo_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Status'),
        ),
        migrations.AlterField(
            model_name='statusinstrumento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_status_instrumentos', to='cadastro.funcionario'),
        ),
    ]
