# Generated by Django 6.0.1 on 2026-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0002_statusinstrumento_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusinstrumento',
            name='data_recebimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Recebimento'),
        ),
    ]
