# Generated by Django 6.0.1 on 2026-01-21 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0003_statusinstrumento_data_recebimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Link do Certificado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('certeza', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Certeza')),
                ('tendencia', models.CharField(blank=True, max_length=100, verbose_name='Tendência')),
                ('resultado', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=10, null=True, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='instrumento.statusinstrumento')),
            ],
            options={
                'verbose_name': 'Certificado de Calibração',
                'verbose_name_plural': 'Certificados de Calibração',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
