# Generated by Django 6.0.1 on 2026-01-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_pontocalibracao_valor_maximo_and_more'),
        ('instrumento', '0004_certificadocalibracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadocalibracao',
            name='certeza',
        ),
        migrations.RemoveField(
            model_name='certificadocalibracao',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='certificadocalibracao',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='certificadocalibracao',
            name='tendencia',
        ),
        migrations.CreateModel(
            name='StatusPontoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incerteza', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Incerteza')),
                ('tendencia', models.CharField(blank=True, max_length=100, verbose_name='Tendência')),
                ('resultado', models.CharField(blank=True, choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=10, null=True, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_pontos', to='instrumento.certificadocalibracao', verbose_name='Certificado de Calibração')),
                ('ponto_calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pontos', to='cadastro.pontocalibracao', verbose_name='Ponto de Calibração')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_pontos_analise', to='cadastro.funcionario', verbose_name='Responsável pela Análise')),
            ],
            options={
                'verbose_name': 'Status do Ponto de Calibração',
                'verbose_name_plural': 'Status dos Pontos de Calibração',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
