# Generated by Django 6.0.1 on 2026-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0005_remove_certificadocalibracao_certeza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspontocalibracao',
            name='media_medicoes',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Média das Medições'),
        ),
    ]
